### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by ZainW** [Akryum/peeky#27]
Hi there, I am unable to install peeky/cli 

I ran the code in the guide [here](https://peeky.netlify.app/guide/) `npm i -D @peeky/cli`

output: 

```sh
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @peeky/config@^0.4.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wood/.npm/_logs/2021-08-31T19_44_51_228Z-debug.log

```

Node version: 14.7.4
npm version: 6.14.14
platform: linux
log debug: [2021-08-31T19_44_51_228Z-debug.log](https://github.com/Akryum/peeky/files/7086473/2021-08-31T19_44_51_228Z-debug.log)

let me know if i can provide any other context or try it on other machines etc

looking forward to trying out this project!

**Comment by Akryum** [comment]
Could you please try again? I had an issue with npm 🙇

**Comment by ZainW** [comment]
works now! tyvm!
