### ISSUE TITLE
tsconfig paths mapping ?

### ISSUE THREAD

**Issue by soulsam480** [Akryum/peeky#36]
```
 ERROR  Running tests failed: Error: Cannot find module 'src/utils/helpers'
```
Hii @Akryum is it possible to support tsconfig paths mapping. I tried doing this but it din't work

```json
    "test:open": "node -r tsconfig-paths/register node_modules/@peeky/cli/dist/index.js open"
```
I used this https://www.npmjs.com/package/tsconfig-paths

**Comment by Akryum** [comment]
Peeky moved to Vite to compile files, so it should respect `vite.config.ts` in your project. I didn't test path mappings yet though
