### ISSUE TITLE
failed to resolve "extends"

### ISSUE THREAD

**Issue by mdbetancourt** [Akryum/peeky#39]
i get Running tests failed: TSConfckParseError: failed to resolve "extends" when i used extends in "tsconfig"

**Comment by Akryum** [comment]
Do you have some reproduction to show us?

**Comment by mdbetancourt** [comment]
i'm afraid could be something related to vite when is used together with rush (maybe in the way pnpm link the packages), i get this error creating a tool on top of vite and the way i fixed it was using typescript builtin tsconfig loader instead of tsconfck

```ts
import { InlineConfig } from 'vite';
import ts from 'typescript';
import { build } from 'vite';

const tsconfigRaw = ts.readConfigFile(tsconfig.value, ts.sys.readFile);

let buildConfig: InlineConfig = {
      // configs
      esbuild: {
        tsconfigRaw: JSON.stringify(tsconfigRaw.config)
      }
};
build(buildConfig)
```
i will create a reproduction repo

**Comment by mdbetancourt** [comment]
i just found out was going on this happens when you are using the base tsconfig from another package but this package does not define the tsconfig in the "exports" field in package.json
