### ISSUE TITLE
slow startup and restart time

### ISSUE THREAD

**Issue by mdbetancourt** [Akryum/peeky#40]
i'm trying this but with just one test i cannot get less than 700ms 

![image](https://user-images.githubusercontent.com/22435967/145316797-8d93edc8-cdcb-4231-b93a-acb2fe3a1e4a.png)

**Comment by Akryum** [comment]
It's on my radar 🐈

**Comment by Akryum** [comment]
It should be much more performance now in [v0.8.0](https://github.com/Akryum/peeky/releases/tag/v0.8.0).
