### ISSUE TITLE
Easily see results from previous runs

### ISSUE THREAD

**Issue by mdbetancourt** [Akryum/peeky#42]
when i save a test file all the others are removed except the file i saved

**Comment by Akryum** [comment]
It's because the new run only ran the test files related to the change. You can browser the previous runs with the menu in the top-left toolbar

**Comment by mdbetancourt** [comment]
but it's annoying if you have 10 files with errors and you saved one then you lost the remaining 9 errors unless you go to the previous run...

**Comment by Akryum** [comment]
I see what you mean

**Comment by Akryum** [comment]
![Uploading Screenshot 2021-12-12 at 00.57.52.png…]()

**Comment by Akryum** [comment]
Available in https://github.com/Akryum/peeky/releases/tag/v0.8.3
