### ISSUE TITLE
Top level `beforeAll`, `beforeEach()`, `afterAll`, and `afterEach`

### ISSUE THREAD

**Issue by posva** [Akryum/peeky#66]
Right now, when these are declared outside of a `describe()`, they don't run. This would be useful to setup o mocking HTTP server like https://mswjs.io/ and adding it to `setupFiles` in the peeky config to automatically add this to all test suites:

```ts
import { server } from './mock/server.ts' // msw specific

beforeAll(() => server.listen())
afterEach(() => server.resetHandlers())
afterAll(() => server.close())
```

**Comment by victorlmneves** [comment]
@posva I'm using it outside a describe() and it's working fine

**Comment by posva** [comment]
I think @Akryum implemented this but forgot to close it
